// <auto-generated />
using System;
using DocumentController.WebAPI.Migrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DocumentController.WebAPI.Migrations
{
    [DbContext(typeof(DocumentControllerDbContext))]
    partial class DocumentControllerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("DocumentController.WebAPI.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Department");

                    b.Property<string>("DocumentNumber");

                    b.Property<string>("Function");

                    b.Property<string>("Location");

                    b.Property<string>("Status");

                    b.Property<string>("Title");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("DocumentController.WebAPI.Models.DocumentVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DescriptionOfChange");

                    b.Property<int>("DocumentId");

                    b.Property<DateTime?>("EffectiveDate");

                    b.Property<string>("IsRemoved");

                    b.Property<string>("Location_Editable");

                    b.Property<string>("Location_PDF");

                    b.Property<string>("Progress");

                    b.Property<string>("PurposeOfChange");

                    b.Property<string>("Remarks");

                    b.Property<string>("Requestor");

                    b.Property<string>("VersionNumber");

                    b.HasKey("Id");

                    b.ToTable("DocumentVersions");
                });
#pragma warning restore 612, 618
        }
    }
}
